name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.ACR_USERNAME }}.azurecr.io/tetris:${{ github.sha }}
          ${{ secrets.ACR_USERNAME }}.azurecr.io/tetris:latest
  
  deploy:
    
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Set private registry authentication settings'
      run: az webapp config container set --name ycetindil --resource-group Tetris --docker-registry-server-user ${{ secrets.ACR_USERNAME }} --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
    
    - name: Deploy to Azure web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ycetindil'
        images: '${{ secrets.ACR_USERNAME }}.azurecr.io/tetris:${{ github.sha }}'
